<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

use AppBundle\Entity\Diary;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * DiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaryRepository extends EntityRepository
{

  public function queryLatest()
  {
    return $this->getEntityManager()
      ->createQuery('
        SELECT d
        FROM AppBundle:Diary d
        WHERE d.diaryDate <= :now
        ORDER BY d.diaryDate DESC
      ')
      ->setParameter('now', new \DateTime());
  }
  
  public function findLatest($page = 1)
  {
    $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest(), false));
    $paginator->setMaxPerPage(Diary::NUM_ITEMS);
    $paginator->setCurrentPage($page);
    return $paginator;
  }
}
